# Generated by Django 3.2.8 on 2022-01-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-username'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
    ]
