# Generated by Django 3.2.8 on 2022-05-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
