# Generated by Django 3.2.8 on 2022-05-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('good', 'Good'), ('suspicius', 'suspicius'), ('banned', 'Banned')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Developer'), (4, 'Common User')], default=4, max_length=20),
        ),
    ]
