# Generated by Django 3.2.8 on 2022-05-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220523_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('good', 'Good'), ('suspicious', 'Suspicious'), ('banned', 'Banned')], default='good', max_length=20, verbose_name='Status'),
        ),
    ]
