# Generated by Django 3.2.6 on 2021-08-20 08:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autocomplete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'autocomplete',
                'verbose_name_plural': 'autocompletions',
            },
        ),
        migrations.CreateModel(
            name='CrawlerPages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_url', models.TextField()),
                ('cr_content', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'crawler page',
                'verbose_name_plural': 'crawler pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerSites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_url', models.TextField()),
                ('robot_txt', models.TextField()),
                ('sitemap_xml', models.TextField()),
                ('domain_name', models.TextField()),
                ('sub_domain_name', models.TextField()),
                ('internal_links', models.TextField()),
                ('external_links', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'crawler site',
                'verbose_name_plural': 'crawler sites',
            },
        ),
        migrations.CreateModel(
            name='FirstIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bs_url', models.TextField()),
                ('bs_links', models.TextField()),
                ('bs_title', models.TextField()),
                ('bs_head', models.TextField()),
                ('bs_cann', models.TextField()),
                ('bs_desc', models.TextField()),
                ('site_lang', models.TextField()),
                ('bs_internal_links', models.TextField()),
                ('bs_external_links', models.TextField()),
                ('site_content', models.TextField()),
                ('site_content_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('bs_title_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'first index',
                'verbose_name_plural': 'first indexes',
            },
        ),
        migrations.CreateModel(
            name='ImageIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.TextField()),
                ('img_alt', models.TextField()),
                ('img_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'image index',
                'verbose_name_plural': 'image indexes',
            },
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'search Results',
                'verbose_name_plural': 'search Results',
            },
        ),
        migrations.AddIndex(
            model_name='imageindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['img_search'], name='core_imagei_img_sea_241f95_gin'),
        ),
        migrations.AddField(
            model_name='firstindex',
            name='cr_first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crawlerpages'),
        ),
        migrations.AddIndex(
            model_name='firstindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['site_content_search', 'bs_title_search'], name='core_firsti_site_co_e79fd2_gin'),
        ),
    ]
