# Generated by Django 3.2.6 on 2021-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Queue for Crawling',
                'verbose_name_plural': 'Queues for Crawling',
            },
        ),
        migrations.AlterModelOptions(
            name='crawlersites',
            options={'verbose_name': 'Crawler Site', 'verbose_name_plural': 'Crawler Sites'},
        ),
        migrations.AlterModelOptions(
            name='firstindex',
            options={'verbose_name': 'First Index', 'verbose_name_plural': 'First Indexes'},
        ),
        migrations.AlterModelOptions(
            name='imageindex',
            options={'verbose_name': 'Image Index', 'verbose_name_plural': 'Image Indexes'},
        ),
        migrations.AlterModelOptions(
            name='searchresults',
            options={'verbose_name': 'Search Results', 'verbose_name_plural': 'Search Results'},
        ),
        migrations.AlterField(
            model_name='autocomplete',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
