# Generated by Django 3.2.6 on 2021-08-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210827_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawlerpages',
            options={'ordering': ['-created_at'], 'verbose_name': 'Crawled Page', 'verbose_name_plural': 'Crawled Pages'},
        ),
    ]
