# Generated by Django 3.2.6 on 2021-09-07 10:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_crawlerpages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSearchIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bs_url', models.TextField()),
                ('bs_links', models.TextField()),
                ('bs_title', models.TextField()),
                ('bs_head', models.TextField()),
                ('bs_cann', models.TextField()),
                ('bs_desc', models.TextField()),
                ('site_lang', models.TextField()),
                ('bs_internal_links', models.TextField()),
                ('bs_external_links', models.TextField()),
                ('site_content', models.TextField()),
                ('keywords', models.TextField()),
                ('site_content_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('bs_title_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('crawler_fk_pages', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'First Index',
                'verbose_name_plural': 'First Indexes',
            },
        ),
        migrations.CreateModel(
            name='SiteSearchIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_url', models.TextField()),
                ('site_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Search Index',
                'verbose_name_plural': 'Site Search Indexes',
            },
        ),
        migrations.CreateModel(
            name='VideoIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_src_url', models.TextField()),
                ('video_type', models.TextField()),
                ('video_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('video_controls', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Index',
                'verbose_name_plural': 'Video Indexes',
            },
        ),
        migrations.RenameModel(
            old_name='ImageIndex',
            new_name='ImageSearchIndex',
        ),
        migrations.RenameModel(
            old_name='SearchResults',
            new_name='SearchQueries',
        ),
        migrations.DeleteModel(
            name='CrawlerSites',
        ),
        migrations.DeleteModel(
            name='CrawlQueue',
        ),
        migrations.RemoveField(
            model_name='firstindex',
            name='cr_first',
        ),
        migrations.RemoveIndex(
            model_name='imagesearchindex',
            name='core_imagei_img_sea_241f95_gin',
        ),
        migrations.AddIndex(
            model_name='imagesearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['img_search'], name='core_images_img_sea_2cf2f5_gin'),
        ),
        migrations.DeleteModel(
            name='CrawlerPages',
        ),
        migrations.DeleteModel(
            name='FirstIndex',
        ),
        migrations.AddIndex(
            model_name='videoindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['video_search'], name='core_videoi_video_s_94629c_gin'),
        ),
        migrations.AddIndex(
            model_name='sitesearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['site_search'], name='core_sitese_site_se_2a0947_gin'),
        ),
        migrations.AddIndex(
            model_name='contentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['site_content_search', 'bs_title_search'], name='core_conten_site_co_3de721_gin'),
        ),
    ]
