# Generated by Django 3.2.6 on 2021-09-07 10:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210907_1224'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentsearchindex',
            name='core_conten_site_co_3de721_gin',
        ),
        migrations.RenameField(
            model_name='contentsearchindex',
            old_name='bs_title_search',
            new_name='bs_etc_search',
        ),
        migrations.AddIndex(
            model_name='contentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['site_content_search', 'bs_etc_search'], name='core_conten_site_co_adbc3c_gin'),
        ),
    ]
