# Generated by Django 3.2.6 on 2021-09-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210907_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_cann',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_external_links',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_head',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_internal_links',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_links',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='site_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='site_lang',
            field=models.TextField(blank=True),
        ),
    ]
