# Generated by Django 3.2.6 on 2021-09-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210923_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_cann',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_external_links',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_head',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_internal_links',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_links',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='bs_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='site_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentsearchindex',
            name='site_lang',
            field=models.TextField(null=True),
        ),
    ]
