# Generated by Django 3.2.6 on 2021-09-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210923_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsearchindex',
            name='bs_cann',
        ),
        migrations.RemoveField(
            model_name='contentsearchindex',
            name='bs_external_links',
        ),
        migrations.RemoveField(
            model_name='contentsearchindex',
            name='bs_head',
        ),
        migrations.RemoveField(
            model_name='contentsearchindex',
            name='bs_internal_links',
        ),
        migrations.RemoveField(
            model_name='contentsearchindex',
            name='bs_links',
        ),
    ]
