# Generated by Django 3.2.6 on 2021-10-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_imagesearchindex_crawler_fk_pages'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentsearchindex',
            name='core_conten_site_co_adbc3c_gin',
        ),
        migrations.RenameField(
            model_name='contentsearchindex',
            old_name='bs_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='contentsearchindex',
            old_name='bs_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='contentsearchindex',
            old_name='bs_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='contentsearchindex',
            name='bs_etc_search',
        ),
        migrations.RemoveField(
            model_name='contentsearchindex',
            name='site_content_search',
        ),
    ]
