# Generated by Django 3.2.6 on 2021-10-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211008_1432'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='imagesearchindex',
            name='core_images_img_sea_2cf2f5_gin',
        ),
        migrations.RemoveIndex(
            model_name='videoindex',
            name='core_videoi_video_s_94629c_gin',
        ),
        migrations.RemoveField(
            model_name='imagesearchindex',
            name='img_search',
        ),
        migrations.RemoveField(
            model_name='videoindex',
            name='video_search',
        ),
    ]
