# Generated by Django 3.2.6 on 2021-10-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211008_1530'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sitesearchindex',
            name='core_sitese_site_se_2a0947_gin',
        ),
        migrations.RemoveField(
            model_name='sitesearchindex',
            name='site_search',
        ),
    ]
