# Generated by Django 3.2.8 on 2022-05-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211013_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autocomplete',
            options={'verbose_name': 'autocomplete', 'verbose_name_plural': 'autocompletion'},
        ),
    ]
