# Generated by Django 3.2.6 on 2021-08-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('results_was_helpful', models.BooleanField()),
                ('results_was_not_helpful', models.BooleanField()),
                ('information_outdated', models.BooleanField()),
                ('information_is_missing', models.BooleanField()),
                ('other_field', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
                'ordering': ['-timestamp'],
            },
        ),
    ]
