# Generated by Django 3.2.6 on 2021-09-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='information_is_missing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='information_outdated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='other_field',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='results_was_helpful',
            field=models.CharField(choices=[('no', 'NO'), ('yes', 'YES')], default='--', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='results_was_not_helpful',
            field=models.BooleanField(null=True),
        ),
    ]
