# Generated by Django 3.2.6 on 2021-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_results_was_helpful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='other_field',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='results_was_helpful',
            field=models.CharField(blank=True, choices=[('no', 'NO'), ('yes', 'YES')], default='empty', max_length=3),
        ),
    ]
