# Generated by Django 3.2.6 on 2021-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20210906_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='information_is_missing',
            field=models.CharField(blank=True, choices=[('no', 'NO'), ('yes', 'YES')], default='empty', max_length=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='information_outdated',
            field=models.CharField(blank=True, choices=[('no', 'NO'), ('yes', 'YES')], default='empty', max_length=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='results_was_not_helpful',
            field=models.CharField(blank=True, choices=[('no', 'NO'), ('yes', 'YES')], default='empty', max_length=3),
        ),
    ]
