# Generated by Django 3.2.6 on 2021-09-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20210906_1420'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
        migrations.AlterModelTable(
            name='support',
            table='support',
        ),
    ]
