# Generated by Django 3.2.6 on 2021-09-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20210910_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('error', models.TextField()),
            ],
            options={
                'verbose_name': 'problem',
                'verbose_name_plural': 'problems',
                'db_table': 'problem',
            },
        ),
    ]
