# Generated by Django 3.2.8 on 2022-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_remove_feedback_results_was_not_helpful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='error',
            field=models.TextField(verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.TextField(verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
