# Generated by Django 3.2.8 on 2022-05-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_auto_20220519_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='support',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='support',
            name='user',
            field=models.CharField(max_length=255, verbose_name='User'),
        ),
    ]
