# Generated by Django 3.2.8 on 2022-05-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
