# Generated by Django 3.2.8 on 2022-05-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_alter_contact_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='information_is_missing',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='empty', max_length=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='information_outdated',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='empty', max_length=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='results_was_helpful',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='empty', max_length=3),
        ),
    ]
