# Generated by Django 3.2.6 on 2021-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerPages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_url', models.TextField()),
                ('cr_content', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crawled Page',
                'verbose_name_plural': 'Crawled Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerSites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_url', models.TextField()),
                ('robot_txt', models.TextField()),
                ('sitemap_xml', models.TextField()),
                ('domain_name', models.TextField()),
                ('sub_domain_name', models.TextField()),
                ('internal_links', models.TextField()),
                ('external_links', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crawler Site',
                'verbose_name_plural': 'Crawler Sites',
            },
        ),
        migrations.CreateModel(
            name='CrawlQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Queue for Crawling',
                'verbose_name_plural': 'Queues for Crawling',
            },
        ),
    ]
