# Generated by Django 3.2.6 on 2021-09-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20210907_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlersites',
            name='optional_field_3',
        ),
        migrations.RemoveField(
            model_name='crawlersites',
            name='optional_field_4',
        ),
        migrations.AddField(
            model_name='crawlersites',
            name='front_page_content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlersites',
            name='sitemap_rss',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
