# Generated by Django 3.2.6 on 2021-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20210919_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerpages',
            name='added_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlersites',
            name='added_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
