# Generated by Django 3.2.8 on 2022-05-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20210923_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlqueue',
            name='added_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
