# Generated by Django 3.2.8 on 2022-06-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_crawlqueue_page_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlqueue',
            name='added_by',
            field=models.IntegerField(),
        ),
    ]
